export interface SeedCategory {
  name: string;
  slug: string;
  description: string;
  iconName: string;
  color: string;
}

export interface SeedVerse {
  number: number;
  lines: string[];
  englishLines?: string[];
}

export interface SeedHymn {
  number: number;
  title: string;
  alternateTitle?: string;
  category: string;
  author: string;
  verses: SeedVerse[];
  chorus?: string[];
  tags: string[];
  meter?: string;
  tune?: string;
  key?: string;
}

export const SEED_CATEGORIES: SeedCategory[] = [
  {
    name: 'Praise',
    slug: 'praise',
    description: 'Songs of exaltation, thanksgiving, and glory to Almighty God.',
    iconName: 'Users',
    color: 'emerald',
  },
  {
    name: 'Worship',
    slug: 'worship',
    description: 'Reverent devotion, deep homage, and honoring the Majesty of God.',
    iconName: 'Music',
    color: 'sky',
  },
  {
    name: 'Grace',
    slug: 'grace',
    description: 'Unmerited favor, redemption, and the boundless love of God.',
    iconName: 'Heart',
    color: 'purple',
  },
  {
    name: 'Prayer',
    slug: 'prayer',
    description: 'Petitions, intercession, calling upon God in humility and trust.',
    iconName: 'HandHeart',
    color: 'indigo',
  },
  {
    name: 'Thanksgiving',
    slug: 'thanksgiving',
    description: 'Offering gratitude for God’s unfailing mercies and providence.',
    iconName: 'Flame',
    color: 'amber',
  },
  {
    name: 'Salvation',
    slug: 'salvation',
    description: 'Redemption through Jesus Christ, repentance, and free forgiveness.',
    iconName: 'Cross',
    color: 'teal',
  },
  {
    name: 'Faith & Trust',
    slug: 'faith-and-trust',
    description: 'Steadfast assurance, leaning on the Everlasting Arms in all seasons.',
    iconName: 'Shield',
    color: 'blue',
  },
  {
    name: 'Christmas',
    slug: 'christmas',
    description: 'Celebrating the birth of Emmanuel and the light of the world.',
    iconName: 'Star',
    color: 'emerald',
  },
  {
    name: 'Easter',
    slug: 'easter',
    description: 'Christ is risen! Victory over death, grave, and sin.',
    iconName: 'Sunrise',
    color: 'yellow',
  },
  {
    name: 'Dedication',
    slug: 'dedication',
    description: 'Consecration of heart, service, and walking in holiness before God.',
    iconName: 'Sparkles',
    color: 'rose',
  },
];

export const HYMN_LYRICS: Record<string, string[]> = {
  amazingGrace: [
    `Amazing grace! how sweet the sound\nThat saved a wretch like me!\nI once was lost, but now am found,\nWas blind, but now I see.`,
    `'Twas grace that taught my heart to fear,\nAnd grace my fears relieved;\nHow precious did that grace appear\nThe hour I first believed!`,
    `Through many dangers, toils, and snares,\nI have already come;\n'Tis grace has brought me safe thus far,\nAnd grace will lead me home.`,
    `The Lord has promised good to me,\nHis Word my hope secures;\nHe will my shield and portion be\nAs long as life endures.`,
    `When we've been there ten thousand years,\nBright shining as the sun,\nWe've no less days to sing God's praise\nThan when we'd first begun.`,
  ],
  allHailThePower: [
    `All hail the power of Jesus' name!\nLet angels prostrate fall;\nBring forth the royal diadem,\nAnd crown Him Lord of all.`,
    `Ye chosen seed of Israel's race,\nYe ransomed from the fall,\nHail Him who saves you by His grace,\nAnd crown Him Lord of all.`,
    `Hail Him, ye heirs of David's line,\nWhom David Lord did call;\nThe Lord incarnate, Man divine:\nAnd crown Him Lord of all.`,
    `Let every kindred, every tribe\nOn this terrestrial ball,\nTo Him all majesty ascribe,\nAnd crown Him Lord of all.`,
  ],
  toGodBeTheGlory: [
    `To God be the glory, great things He hath done;\nSo loved He the world that He gave us His Son,\nWho yielded His life an atonement for sin,\nAnd opened the life-gate that all may go in.`,
    `O perfect redemption, the purchase of blood,\nTo every believer the promise of God;\nThe vilest offender who truly believes,\nThat moment from Jesus a pardon receives.`,
    `Great things He hath taught us, great things He hath done,\nAnd great our rejoicing through Jesus the Son;\nBut purer, and higher, and greater will be\nOur wonder, our transport, when Jesus we see.`,
  ],
  praiseToTheLord: [
    `Praise to the Lord, the Almighty, the King of creation!\nO my soul, praise Him, for He is thy health and salvation!\nAll ye who hear, now to His temple draw near;\nPraise Him in glad adoration.`,
    `Praise to the Lord! who o'er all things so wondrously reigneth,\nShelters thee under His wings, yea, so gently sustaineth;\nHast thou not seen how thy desires e'er have been\nGranted in what He ordaineth?`,
    `Praise to the Lord! Who doth prosper thy work and defend thee;\nSurely His goodness and mercy here daily attend thee.\nPonder anew what the Almighty can do,\nIf with His love He befriend thee!`,
  ],
  oForAThousandTongues: [
    `O for a thousand tongues to sing\nMy great Redeemer's praise,\nThe glories of my God and King,\nThe triumphs of His grace!`,
    `My gracious Master and my God,\nAssist me to proclaim,\nTo spread through all the earth abroad\nThe honors of Thy Name.`,
    `Jesus, the Name that charms our fears,\nThat bids our sorrows cease;\n'Tis music in the sinner's ears,\n'Tis life, and health, and peace.`,
  ],
  crownHimWithManyCrowns: [
    `Crown Him with many crowns,\nThe Lamb upon His throne;\nHark! how the heavenly anthem drowns\nAll music but its own!\nAwake, my soul, and sing of Him who died for thee,\nAnd hail Him as thy matchless King through all eternity.`,
    `Crown Him the Lord of life,\nWho triumphed o'er the grave,\nAnd rose victorious in the strife\nFor those He came to save;\nHis glories now we sing, who died and rose on high,\nWho died eternal life to bring, and lives that death may die.`,
  ],
  holyHolyHoly: [
    `Holy, Holy, Holy, Lord God Almighty!\nEarly in the morning our song shall rise to Thee;\nHoly, Holy, Holy! merciful and mighty;\nGod in Three Persons, Blessed Trinity!`,
    `Holy, Holy, Holy! all the saints adore Thee,\nCasting down their golden crowns around the glassy sea;\nCherubim and Seraphim falling down before Thee,\nWhich wert, and art, and evermore shalt be.`,
    `Holy, Holy, Holy! Lord God Almighty!\nAll Thy works shall praise Thy Name, in earth and sky, and sea;\nHoly, Holy, Holy! merciful and mighty,\nGod in three Persons, blessed Trinity!`,
  ],
  fairestLordJesus: [
    `Fairest Lord Jesus! Ruler of all nature!\nO Thou of God and man the Son!\nThee will I cherish, Thee will I honor,\nThou, my soul's glory, joy and crown.`,
    `Fair are the meadows, fairer still the woodlands,\nRobed in the blooming garb of spring,\nJesus is fairer, Jesus is purer,\nWho makes the woeful heart to sing.`,
    `Fair is the sunshine, fairer still the moonlight,\nAnd all the twinkling starry hosts:\nJesus shines brighter, Jesus shines purer,\nThan all the angels heav'n can boast.`,
  ],
  beThouMyVision: [
    `Be Thou my vision, O Lord of my heart;\nNaught be all else to me, save that Thou art:\nThou my best thought, by day or by night,\nWaking or sleeping, Thy presence my light.`,
    `Be Thou my wisdom and Thou my true word;\nI ever with Thee and Thou with me, Lord:\nThou my great Father, and I Thy true son,\nThou in me dwelling, and I with Thee, one.`,
    `Riches I heed not, nor man's empty praise,\nThou my inheritance now and always:\nThou and Thou only are first in my heart,\nHigh King of heaven, my treasure Thou art.`,
  ],
  graceGreaterThanOurSin: [
    `Marvelous grace of our loving Lord,\nGrace that exceeds our sin and our guilt,\nYonder on Calvary's mount outpoured,\nThere where the blood of the Lamb was shed.`,
    `Dark is the stain that we cannot hide,\nWhat can avail to wash it away?\nLook! there is flowing a crimson tide;\nWhiter than snow you may be today.`,
    `Marvelous, infinite, matchless grace,\nFreely bestowed on all who believe;\nYou that are long-ing to see His face,\nWill you this moment His grace receive?`,
  ],
  jesusPaidItAll: [
    `I hear the Savior say,\n"Thy strength indeed is small;\nChild of weakness, watch and pray,\nFind in Me thine all in all."`,
    `Lord, now indeed I find\nThy pow'r, and Thine alone,\nCan change the leper's spots,\nAnd melt the heart of stone.`,
    `And when, before the throne,\nI stand in Him complete,\n"Jesus died my soul to save,"\nMy lips shall still repeat.`,
  ],
  rockOfAgesCleftForMe: [
    `Rock of Ages, cleft for me,\nLet me hide myself in Thee;\nLet the water and the blood,\nFrom Thy wounded side which flowed,\nBe of sin the double cure,\nSave from wrath and make me pure.`,
    `Could my tears forever flow,\nCould my zeal no languor know,\nThese for sin could not atone;\nThou must save, and Thou alone:\nIn my hand no price I bring,\nSimply to Thy cross I cling.`,
    `While I draw this fleeting breath,\nWhen my eyes shall close in death,\nWhen I rise to worlds unknown,\nAnd behold Thee on Thy throne,\nRock of Ages, cleft for me,\nLet me hide myself in Thee.`,
  ],
  nothingButTheBlood: [
    `What can wash away my sins?\nNothing but the blood of Jesus;\nWhat can make me whole again,\nNothing but the blood of Jesus.`,
    `For my portion this I see,\nNothing but the blood of Jesus;\nFor my cleansing, this my plea,\nNothing but the blood of Jesus.`,
    `Nothing can for sin atone,\nNothing but the blood of Jesus;\nNaught of good that I have done,\nNothing but the blood of Jesus.`,
  ],
  justAsIAmWithoutOnePlea: [
    `Just as I am, without one plea,\nBut that Thy blood was shed for me,\nAnd that Thou bid'st me come to Thee,\nO Lamb of God, I come, I come.`,
    `Just as I am and waiting not,\nTo rid my soul of one dark blot,\nTo Thee whose blood can cleanse each thought,\nO Lamb of God I come, I come.`,
    `Just as I am Thou wilt receive,\nWilt welcome, pardon, cleanse, relieve;\nBecause Thy promise I believe,\nO Lamb of God, I come, I come.`,
  ],
  andCanItBe: [
    `And can it be that I should gain\nAn int'rest in my Savior's blood?\nDied He for me, who caused His pain?\nFor me, who scorned His perfect love?`,
    `He left His Father's throne above,\nSo free, so infinite His grace;\nEmptied Himself of all but love,\nAnd bled for Adam's helpless race.`,
    `Boldly I come before Your throne,\nTo claim Your mercy immense and free;\nNo greater love will e'er be known,\nFor O, my God, it found out me.`,
  ],
  blessedAssurance: [
    `Blessed assurance, Jesus is mine!\nOh, what a foretaste of glory divine!\nHeir of salvation, purchase of God,\nBorn of His Spirit, washed in His blood.`,
    `Perfect submission, perfect delight,\nVisions of rapture now burst on my sight;\nAngels descending, bring from above,\nEchoes of mercy, whispers of love.`,
    `Perfect submission, all is at rest,\nI in my Savior am happy and blest;\nWatching and waiting, looking above,\nFilled with His goodness, lost in His love.`,
  ],
  tisSoSweetToTrustInJesus: [
    `Tis so sweet to trust in Jesus,\nJust to take Him at His word;\nJust to rest upon His promise,\nJust to know, "Thus saith the Lord."`,
    `O how sweet to trust in Jesus,\nJust to trust His cleansing blood;\nJust in simple faith to plunge me\n'Neath the healing, cleansing flood.`,
    `I'm so glad I learned to trust Thee,\nPrecious Jesus, Savior, Friend;\nAnd I know that Thou art with me,\nWilt be with me to the end.`,
  ],
  standingOnThePromises: [
    `Standing on the promises of Christ my King,\nThru eternal ages let His praises ring;\nGlory in the highest, I will shout and sing,\nStanding on the promises of God.`,
    `Standing on the promises that cannot fail,\nWhen the howling storms of doubt and fear assail,\nBy the living word of God I shall prevail,\nStanding on the promises of God.`,
  ],
  aMightyFortressIsOurGod: [
    `A mighty fortress is our God,\nA bulwark never failing;\nOur helper He amid the flood\nOf mortal ills prevailing.`,
    `Did we in our own strength confide\nOur striving would be losing;\nWere not the right one on our side,\nThe Man of God's own choosing.`,
    `And tho' this world with evil filled,\nShould threaten to undo us;\nWe will not fear, for God hath willed\nHis truth to triumph through us.`,
  ],
  howFirmAFoundation: [
    `How firm a foundation ye saints of the Lord,\nIs laid for your faith in His excellent Word!\nWhat more can He say than to you He hath said,\nYou who unto Jesus for refuge have fled?`,
    `Fear not, I am with thee, O be not dismayed;\nFor I am thy God and will still give thee aid;\nI'll strengthen thee, help thee, and cause thee to stand,\nUpheld by My righteous, omnipotent hand.`,
  ],
  trustAndObey: [
    `When we walk with the Lord in the light of His Word,\nWhat a glory He sheds on our way!\nWhile we do His good will, He abides with us still,\nAnd with all who will trust and obey.`,
    `Not a burden we bear, not a sorrow we share,\nBut our toil He doth richly repay;\nNot a grief nor a loss, not a frown nor a cross,\nBut is blest if we trust and obey.`,
    `Then in fellowship sweet we will sit at His feet,\nOr we'll walk by His side in the way;\nWhat He says we will do, where He sends we will go,\nNever fear, only trust and obey.`,
  ],
  whatAFriendWeHaveInJesus: [
    `What a friend we have in Jesus,\nAll our sins and griefs to bear!\nWhat a privilege to carry\nEverything to God in prayer!`,
    `Have we trials and temptations?\nIs there trouble anywhere?\nWe should never be discouraged,\nTake it to the Lord in prayer.`,
    `Are we weak and heavy laden,\nCumbered with a load of care?\nPrecious Savior, still our refuge,\nTake it to the Lord in prayer.`,
  ],
  sweetHourOfPrayer: [
    `Sweet hour of prayer! sweet hour of prayer!\nThat calls me from a world of care,\nAnd bids me at my Father's throne\nMake all my wants and wishes known.`,
    `Sweet hour of prayer! sweet hour of prayer!\nThe joys I feel, the bliss I share\nOf those whose anxious spirits burn\nWith strong desires for thy return!`,
  ],
  passMeNotOGentleSavior: [
    `Pass me not, O gentle Savior,\nHear my humble cry;\nWhile on others Thou art calling,\nDo not pass me by.`,
    `Let me at Thy throne of mercy\nFind a sweet relief;\nKneeling there in deep contrition,\nHelp my unbelief.`,
    `Thou the spring of all my comfort,\nMore than life to me,\nWhom have I on earth beside Thee?\nWhom in heav'n but Thee?`,
  ],
  iNeedTheeEveryHour: [
    `I need Thee every hour, most gracious Lord;\nNo tender voice like Thine can peace afford.`,
    `I need Thee every hour, stay Thou nearby;\nTemptations lose their power when Thou art nigh.`,
    `I need Thee every hour, in joy or pain;\nCome quickly and abide, or life is vain.`,
    `I need Thee every hour, most Holy One;\nO make me Thine indeed, Thou blessed Son!`,
  ],
  takeMyLifeAndLetItBe: [
    `Take my life, and let it be consecrated, Lord, to Thee;\nTake my moments and my days, let them flow in ceaseless praise.`,
    `Take my hands, and let them move at the impulse of Thy love;\nTake my feet and let them be swift and beautiful for Thee.`,
    `Take my will, and make it Thine: it shall be no longer mine;\nTake my heart it is Thine own: it shall be Thy royal throne.`,
  ],
  saviorLikeAShepherdLeadUs: [
    `Savior, like a shepherd lead us, much we need Thy tender care;\nIn Thy pleasant pastures feed us, for our use Thy folds prepare.`,
    `We are Thine, do Thou befriend us, be the guardian of our way;\nKeep Thy flock, from sin defend us, seek us when we go astray.`,
  ],
  nearerMyGodToThee: [
    `Nearer, my God, to Thee, nearer to Thee!\nE'en though it be a cross that raiseth me,\nStill all my song shall be, nearer, my God, to Thee!`,
    `Though like the wanderer, the sun gone down,\nDarkness be over me, my rest a stone;\nYet in my dreams I'd be nearer, my God, to Thee!`,
  ],
  countYourBlessings: [
    `When upon life's billows you are tempest-tossed,\nWhen you are discouraged, thinking all is lost,\nCount your many blessings, name them one by one,\nAnd it will surprise you what the Lord hath done.`,
    `Are you ever burdened with a load of care?\nDoes the cross seem heavy you are called to bear?\nCount your many blessings, every doubt will fly,\nAnd you will be singing as the days go by.`,
  ],
  forTheBeautyOfTheEarth: [
    `For the beauty of the earth, for the glory of the skies,\nFor the love which from our birth over and around us lies,\nLord of all, to Thee we raise this our hymn of grateful praise.`,
    `For the joy of human love, brother, sister, parent, child,\nFriends on earth and friends above, for all gentle thoughts and mild,\nLord of all, to Thee we raise this our hymn of grateful praise.`,
  ],
  praiseGodFromWhomAllBlessingsFlow: [
    `Praise God, from whom all blessings flow;\nPraise Him, all creatures here below;\nPraise Him above, ye heav'nly host;\nPraise Father, Son, and Holy Ghost.`,
  ],
  joyToTheWorld: [
    `Joy to the world! the Lord is come;\nLet earth receive her King;\nLet every heart prepare Him room,\nAnd heav'n and nature sing.`,
    `Joy to the earth! the Savior reigns;\nLet men their songs employ;\nWhile fields and floods, rocks, hills and plains\nRepeat the sounding joy.`,
    `He rules the world with truth and grace,\nAnd makes the nations prove\nThe glories of His righteousness,\nAnd wonders of His love.`,
  ],
  oComeAllYeFaithful: [
    `O come, all ye faithful, joyful and triumphant,\nO come ye, O come ye to Bethlehem;\nCome and behold Him, born the King of angels;\nO come, let us adore Him, Christ the Lord!`,
    `Sing, choirs of angels, sing in exultation,\nO sing, all ye citizens of heav'n above;\nGlory to God, all glory in the highest;\nO come, let us adore Him, Christ the Lord!`,
  ],
  harkTheHeraldAngelsSing: [
    `Hark! the herald angels sing, "Glory to the newborn King!\nPeace on earth and mercy mild, God and sinners reconciled!"\nJoyful, all ye nations, rise, join the triumph of the skies;\nWith angelic host proclaim, "Christ is born in Bethlehem!"`,
    `Hail the heaven-born Prince of Peace! Hail the Sun of Righteousness!\nLight and life to all He brings, ris'n with healing in His wings.\nMild He lays His glory by, born that man no more may die.`,
  ],
  silentNight: [
    `Silent night, holy night, all is calm, all is bright\nRound yon virgin mother and Child.\nHoly Infant so tender and mild, sleep in heavenly peace.`,
    `Silent night, holy night, shepherds quake at the sight;\nGlories stream from heaven afar,\nHeavenly hosts sing Alleluia! Christ the Savior is born!`,
    `Silent night, holy night, Son of God, love's pure light;\nRadiant beams from Thy holy face,\nWith the dawn of redeeming grace, Jesus, Lord, at Thy birth.`,
  ],
  christTheLordIsRisenToday: [
    `Christ the Lord is ris'n today, Alleluia!\nSons of men and angels say, Alleluia!\nRaise your joys and triumphs high, Alleluia!\nSing, ye heav'ns, and earth reply, Alleluia!`,
    `Lives again our glorious King, Alleluia!\nWhere, O death, is now thy sting? Alleluia!\nOnce He died our souls to save, Alleluia!\nWhere thy victory, O grave? Alleluia!`,
  ],
  theStrifeIsOerTheBattleDone: [
    `The strife is o'er, the battle done;\nThe victory of life is won;\nThe song of triumph has begun: Alleluia!`,
    `The powers of death have done their worst,\nBut Christ their legions hath dispersed;\nLet shouts of holy joy outburst: Alleluia!`,
    `He closed the yawning gates of hell;\nThe bars from heav'n's high portals fell;\nLet hymns of praise His triumph tell: Alleluia!`,
  ],
};

function buildVerses(linesArray: string[]): SeedVerse[] {
  return linesArray.map((verseText, index) => ({
    number: index + 1,
    lines: verseText.split('\n'),
  }));
}

export const SEED_HYMNS: SeedHymn[] = [
  {
    number: 1,
    title: 'Amazing Grace',
    alternateTitle: 'How Sweet the Sound',
    category: 'Grace',
    author: 'John Newton',
    verses: buildVerses(HYMN_LYRICS.amazingGrace),
    tags: ['grace', 'salvation', 'redemption', 'testimony'],
    meter: 'C.M. (8.6.8.6)',
    tune: 'New Britain',
    key: 'G Major',
  },
  {
    number: 2,
    title: 'Holy, Holy, Holy',
    alternateTitle: 'Lord God Almighty',
    category: 'Worship',
    author: 'Reginald Heber',
    verses: buildVerses(HYMN_LYRICS.holyHolyHoly),
    tags: ['trinity', 'holiness', 'adoration', 'morning'],
    meter: '11.12.12.10',
    tune: 'Nicaea',
    key: 'E Flat Major',
  },
  {
    number: 3,
    title: 'To God Be The Glory',
    alternateTitle: 'Great Things He Hath Done',
    category: 'Praise',
    author: 'Fanny J. Crosby',
    verses: buildVerses(HYMN_LYRICS.toGodBeTheGlory),
    chorus: [
      'Praise the Lord, praise the Lord, let the earth hear His voice!',
      'Praise the Lord, praise the Lord, let the people rejoice!',
      'O come to the Father through Jesus the Son,',
      'And give Him the glory, great things He hath done!',
    ],
    tags: ['praise', 'thanksgiving', 'redemption'],
    meter: '11.11.11.11 with Refrain',
    tune: 'To God Be the Glory',
    key: 'A Flat Major',
  },
  {
    number: 4,
    title: 'All Hail the Power of Jesus’ Name',
    alternateTitle: 'Coronation',
    category: 'Praise',
    author: 'Edward Perronet',
    verses: buildVerses(HYMN_LYRICS.allHailThePower),
    tags: ['praise', 'kingship', 'adoration'],
    meter: 'C.M. (8.6.8.6)',
    tune: 'Coronation',
    key: 'G Major',
  },
  {
    number: 5,
    title: 'Praise to the Lord, the Almighty',
    alternateTitle: 'King of Creation',
    category: 'Praise',
    author: 'Joachim Neander',
    verses: buildVerses(HYMN_LYRICS.praiseToTheLord),
    tags: ['praise', 'creation', 'worship'],
    meter: '14.14.4.7.8',
    tune: 'Lobe den Herren',
    key: 'F Major',
  },
  {
    number: 6,
    title: 'O for a Thousand Tongues to Sing',
    alternateTitle: 'The Glories of My God and King',
    category: 'Praise',
    author: 'Charles Wesley',
    verses: buildVerses(HYMN_LYRICS.oForAThousandTongues),
    tags: ['praise', 'redemption', 'joy'],
    meter: 'C.M. (8.6.8.6)',
    tune: 'Azmon',
    key: 'G Major',
  },
  {
    number: 7,
    title: 'Crown Him with Many Crowns',
    alternateTitle: 'The Lamb upon His Throne',
    category: 'Worship',
    author: 'Matthew Bridges',
    verses: buildVerses(HYMN_LYRICS.crownHimWithManyCrowns),
    tags: ['worship', 'royalty', 'easter'],
    meter: 'D.S.M. (6.6.8.6.D)',
    tune: 'Diademata',
    key: 'D Major',
  },
  {
    number: 8,
    title: 'Fairest Lord Jesus',
    alternateTitle: 'Ruler of All Nature',
    category: 'Worship',
    author: 'Münster Gesangbuch',
    verses: buildVerses(HYMN_LYRICS.fairestLordJesus),
    tags: ['worship', 'devotion', 'beauty'],
    meter: '5.5.7.5.5.8',
    tune: 'Crusaders’ Hymn',
    key: 'E Flat Major',
  },
  {
    number: 9,
    title: 'Be Thou My Vision',
    alternateTitle: 'Lord of My Heart',
    category: 'Prayer',
    author: 'Dallán Forgaill',
    verses: buildVerses(HYMN_LYRICS.beThouMyVision),
    tags: ['prayer', 'guidance', 'vision', 'devotion'],
    meter: '10.10.10.10',
    tune: 'Slane',
    key: 'E Flat Major',
  },
  {
    number: 10,
    title: 'Grace Greater than Our Sin',
    alternateTitle: 'Marvelous Grace of Our Loving Lord',
    category: 'Grace',
    author: 'Julia H. Johnston',
    verses: buildVerses(HYMN_LYRICS.graceGreaterThanOurSin),
    tags: ['grace', 'forgiveness', 'calvary'],
    meter: '9.9.9.9 with Refrain',
    tune: 'Moody',
    key: 'G Major',
  },
  {
    number: 11,
    title: 'Jesus Paid It All',
    alternateTitle: 'I Hear the Savior Say',
    category: 'Salvation',
    author: 'Elvina M. Hall',
    verses: buildVerses(HYMN_LYRICS.jesusPaidItAll),
    tags: ['salvation', 'blood', 'cross'],
    meter: '6.6.8.6 with Refrain',
    tune: 'All to Christ',
    key: 'E Flat Major',
  },
  {
    number: 12,
    title: 'Rock of Ages, Cleft for Me',
    alternateTitle: 'Let Me Hide Myself in Thee',
    category: 'Salvation',
    author: 'Augustus Toplady',
    verses: buildVerses(HYMN_LYRICS.rockOfAgesCleftForMe),
    tags: ['salvation', 'refuge', 'security'],
    meter: '7.7.7.7.7.7',
    tune: 'Toplady',
    key: 'B Flat Major',
  },
  {
    number: 13,
    title: 'Nothing but the Blood of Jesus',
    alternateTitle: 'What Can Wash Away My Sin',
    category: 'Salvation',
    author: 'Robert Lowry',
    verses: buildVerses(HYMN_LYRICS.nothingButTheBlood),
    tags: ['salvation', 'atonement', 'cleansing'],
    meter: '7.8.7.8 with Refrain',
    tune: 'Plainfield',
    key: 'F Major',
  },
  {
    number: 14,
    title: 'Just As I Am, Without One Plea',
    alternateTitle: 'O Lamb of God, I Come',
    category: 'Salvation',
    author: 'Charlotte Elliott',
    verses: buildVerses(HYMN_LYRICS.justAsIAmWithoutOnePlea),
    tags: ['salvation', 'invitation', 'repentance'],
    meter: '8.8.8.6',
    tune: 'Woodworth',
    key: 'E Flat Major',
  },
  {
    number: 15,
    title: 'And Can It Be That I Should Gain',
    alternateTitle: 'Amazing Love, How Can It Be',
    category: 'Grace',
    author: 'Charles Wesley',
    verses: buildVerses(HYMN_LYRICS.andCanItBe),
    tags: ['grace', 'freedom', 'cross'],
    meter: '8.8.8.8.8.8',
    tune: 'Sagina',
    key: 'G Major',
  },
  {
    number: 16,
    title: 'Blessed Assurance',
    alternateTitle: 'Jesus Is Mine',
    category: 'Faith & Trust',
    author: 'Fanny J. Crosby',
    verses: buildVerses(HYMN_LYRICS.blessedAssurance),
    tags: ['faith', 'assurance', 'joy'],
    meter: '9.10.9.9 with Refrain',
    tune: 'Assurance',
    key: 'D Major',
  },
  {
    number: 17,
    title: '’Tis So Sweet to Trust in Jesus',
    alternateTitle: 'Just to Take Him at His Word',
    category: 'Faith & Trust',
    author: 'Louisa M. R. Stead',
    verses: buildVerses(HYMN_LYRICS.tisSoSweetToTrustInJesus),
    tags: ['faith', 'trust', 'peace'],
    meter: '8.7.8.7 with Refrain',
    tune: 'Trust in Jesus',
    key: 'A Flat Major',
  },
  {
    number: 18,
    title: 'Standing on the Promises',
    alternateTitle: 'Promises of Christ My King',
    category: 'Faith & Trust',
    author: 'Russell Kelso Carter',
    verses: buildVerses(HYMN_LYRICS.standingOnThePromises),
    tags: ['faith', 'promises', 'triumph'],
    meter: '11.11.11.9 with Refrain',
    tune: 'Promises',
    key: 'B Flat Major',
  },
  {
    number: 19,
    title: 'A Mighty Fortress Is Our God',
    alternateTitle: 'Ein feste Burg',
    category: 'Faith & Trust',
    author: 'Martin Luther',
    verses: buildVerses(HYMN_LYRICS.aMightyFortressIsOurGod),
    tags: ['faith', 'strength', 'victory', 'warfare'],
    meter: '8.7.8.7.6.6.6.6.7',
    tune: 'Ein feste Burg',
    key: 'C Major',
  },
  {
    number: 20,
    title: 'How Firm a Foundation',
    alternateTitle: 'Ye Saints of the Lord',
    category: 'Faith & Trust',
    author: 'John Rippon',
    verses: buildVerses(HYMN_LYRICS.howFirmAFoundation),
    tags: ['faith', 'scripture', 'comfort'],
    meter: '11.11.11.11',
    tune: 'Protection',
    key: 'A Flat Major',
  },
  {
    number: 21,
    title: 'Trust and Obey',
    alternateTitle: 'When We Walk with the Lord',
    category: 'Faith & Trust',
    author: 'John H. Sammis',
    verses: buildVerses(HYMN_LYRICS.trustAndObey),
    tags: ['faith', 'obedience', 'fellowship'],
    meter: '6.6.9.D with Refrain',
    tune: 'Trust and Obey',
    key: 'F Major',
  },
  {
    number: 22,
    title: 'What a Friend We Have in Jesus',
    alternateTitle: 'All Our Sins and Griefs to Bear',
    category: 'Prayer',
    author: 'Joseph M. Scriven',
    verses: buildVerses(HYMN_LYRICS.whatAFriendWeHaveInJesus),
    tags: ['prayer', 'comfort', 'friendship'],
    meter: '8.7.8.7.D',
    tune: 'Converse',
    key: 'F Major',
  },
  {
    number: 23,
    title: 'Sweet Hour of Prayer',
    alternateTitle: 'Calls Me from a World of Care',
    category: 'Prayer',
    author: 'William W. Walford',
    verses: buildVerses(HYMN_LYRICS.sweetHourOfPrayer),
    tags: ['prayer', 'peace', 'communion'],
    meter: 'L.M.D. (8.8.8.8.D)',
    tune: 'Sweet Hour',
    key: 'D Major',
  },
  {
    number: 24,
    title: 'Pass Me Not, O Gentle Savior',
    alternateTitle: 'Hear My Humble Cry',
    category: 'Prayer',
    author: 'Fanny J. Crosby',
    verses: buildVerses(HYMN_LYRICS.passMeNotOGentleSavior),
    tags: ['prayer', 'mercy', 'intercession'],
    meter: '8.5.8.5 with Refrain',
    tune: 'Pass Me Not',
    key: 'A Flat Major',
  },
  {
    number: 25,
    title: 'I Need Thee Every Hour',
    alternateTitle: 'Most Gracious Lord',
    category: 'Prayer',
    author: 'Annie S. Hawks',
    verses: buildVerses(HYMN_LYRICS.iNeedTheeEveryHour),
    tags: ['prayer', 'dependence', 'holiness'],
    meter: '6.4.6.4 with Refrain',
    tune: 'Need',
    key: 'A Flat Major',
  },
  {
    number: 26,
    title: 'Take My Life and Let It Be',
    alternateTitle: 'Consecrated Lord to Thee',
    category: 'Dedication',
    author: 'Frances Ridley Havergal',
    verses: buildVerses(HYMN_LYRICS.takeMyLifeAndLetItBe),
    tags: ['dedication', 'consecration', 'service'],
    meter: '7.7.7.7',
    tune: 'Hendon',
    key: 'F Major',
  },
  {
    number: 27,
    title: 'Savior, Like a Shepherd Lead Us',
    alternateTitle: 'Blessed Jesus',
    category: 'Prayer',
    author: 'Dorothy A. Thrupp',
    verses: buildVerses(HYMN_LYRICS.saviorLikeAShepherdLeadUs),
    tags: ['prayer', 'guidance', 'shepherd'],
    meter: '8.7.8.7.8.7',
    tune: 'Bradbury',
    key: 'E Flat Major',
  },
  {
    number: 28,
    title: 'Nearer, My God, to Thee',
    alternateTitle: 'E’en Though It Be a Cross',
    category: 'Prayer',
    author: 'Sarah F. Adams',
    verses: buildVerses(HYMN_LYRICS.nearerMyGodToThee),
    tags: ['prayer', 'comfort', 'closeness'],
    meter: '6.4.6.4.6.6.4',
    tune: 'Bethany',
    key: 'G Major',
  },
  {
    number: 29,
    title: 'Count Your Blessings',
    alternateTitle: 'Name Them One by One',
    category: 'Thanksgiving',
    author: 'Johnson Oatman Jr.',
    verses: buildVerses(HYMN_LYRICS.countYourBlessings),
    tags: ['thanksgiving', 'gratitude', 'joy'],
    meter: '11.11.11.11 with Refrain',
    tune: 'Blessings',
    key: 'E Flat Major',
  },
  {
    number: 30,
    title: 'For the Beauty of the Earth',
    alternateTitle: 'Glory of the Skies',
    category: 'Thanksgiving',
    author: 'Folliott S. Pierpoint',
    verses: buildVerses(HYMN_LYRICS.forTheBeautyOfTheEarth),
    tags: ['thanksgiving', 'creation', 'gratitude'],
    meter: '7.7.7.7.7.7',
    tune: 'Dix',
    key: 'A Flat Major',
  },
  {
    number: 31,
    title: 'Praise God, from Whom All Blessings Flow',
    alternateTitle: 'The Doxology',
    category: 'Praise',
    author: 'Thomas Ken',
    verses: buildVerses(HYMN_LYRICS.praiseGodFromWhomAllBlessingsFlow),
    tags: ['praise', 'trinity', 'doxology'],
    meter: 'L.M. (8.8.8.8)',
    tune: 'Old 100th',
    key: 'G Major',
  },
  {
    number: 32,
    title: 'Joy to the World!',
    alternateTitle: 'The Lord Is Come',
    category: 'Christmas',
    author: 'Isaac Watts',
    verses: buildVerses(HYMN_LYRICS.joyToTheWorld),
    tags: ['christmas', 'incarnation', 'advent', 'joy'],
    meter: 'C.M. (8.6.8.6)',
    tune: 'Antioch',
    key: 'D Major',
  },
  {
    number: 33,
    title: 'O Come, All Ye Faithful',
    alternateTitle: 'Adeste Fideles',
    category: 'Christmas',
    author: 'John Francis Wade',
    verses: buildVerses(HYMN_LYRICS.oComeAllYeFaithful),
    tags: ['christmas', 'adoration', 'angels'],
    meter: 'Irregular',
    tune: 'Adeste Fideles',
    key: 'G Major',
  },
  {
    number: 34,
    title: 'Hark! The Herald Angels Sing',
    alternateTitle: 'Glory to the Newborn King',
    category: 'Christmas',
    author: 'Charles Wesley',
    verses: buildVerses(HYMN_LYRICS.harkTheHeraldAngelsSing),
    tags: ['christmas', 'peace', 'angels'],
    meter: '7.7.7.7.D with Refrain',
    tune: 'Mendelssohn',
    key: 'F Major',
  },
  {
    number: 35,
    title: 'Silent Night, Holy Night',
    alternateTitle: 'All Is Calm, All Is Bright',
    category: 'Christmas',
    author: 'Joseph Mohr',
    verses: buildVerses(HYMN_LYRICS.silentNight),
    tags: ['christmas', 'peace', 'nativity'],
    meter: 'Irregular',
    tune: 'Stille Nacht',
    key: 'B Flat Major',
  },
  {
    number: 36,
    title: 'Christ the Lord Is Risen Today',
    alternateTitle: 'Hallelujah!',
    category: 'Easter',
    author: 'Charles Wesley',
    verses: buildVerses(HYMN_LYRICS.christTheLordIsRisenToday),
    tags: ['easter', 'resurrection', 'triumph'],
    meter: '7.7.7.7 with Alleluias',
    tune: 'Easter Hymn',
    key: 'C Major',
  },
  {
    number: 37,
    title: 'The Strife Is O’er, the Battle Done',
    alternateTitle: 'The Victory of Life Is Won',
    category: 'Easter',
    author: 'Francis Pott',
    verses: buildVerses(HYMN_LYRICS.theStrifeIsOerTheBattleDone),
    tags: ['easter', 'victory', 'alleluia'],
    meter: '8.8.8 with Alleluias',
    tune: 'Victory',
    key: 'D Major',
  },
  {
    number: 38,
    title: 'Great Is Thy Faithfulness',
    alternateTitle: 'O God My Father',
    category: 'Faith & Trust',
    author: 'Thomas O. Chisholm',
    verses: [
      {
        number: 1,
        lines: [
          'Great is Thy faithfulness, O God my Father,',
          'There is no shadow of turning with Thee;',
          'Thou changest not, Thy compassions, they fail not;',
          'As Thou hast been Thou forever wilt be.',
        ],
      },
      {
        number: 2,
        lines: [
          'Summer and winter, and springtime and harvest,',
          'Sun, moon and stars in their courses above,',
          'Join with all nature in manifold witness',
          'To Thy great faithfulness, mercy and love.',
        ],
      },
      {
        number: 3,
        lines: [
          'Pardon for sin and a peace that endureth,',
          'Thine own dear presence to cheer and to guide;',
          'Strength for today and bright hope for tomorrow,',
          'Blessings all mine, with ten thousand beside!',
        ],
      },
    ],
    chorus: [
      'Great is Thy faithfulness! Great is Thy faithfulness!',
      'Morning by morning new mercies I see;',
      'All I have needed Thy hand hath provided;',
      'Great is Thy faithfulness, Lord, unto me!',
    ],
    tags: ['faith', 'faithfulness', 'mercy', 'morning'],
    meter: '11.10.11.10 with Refrain',
    tune: 'Faithfulness',
    key: 'E Flat Major',
  },
  {
    number: 39,
    title: 'It Is Well with My Soul',
    alternateTitle: 'When Peace Like a River',
    category: 'Faith & Trust',
    author: 'Horatio G. Spafford',
    verses: [
      {
        number: 1,
        lines: [
          'When peace like a river attendeth my way,',
          'When sorrows like sea billows roll;',
          'Whatever my lot, Thou hast taught me to say,',
          'It is well, it is well with my soul.',
        ],
      },
      {
        number: 2,
        lines: [
          'Though Satan should buffet, though trials should come,',
          'Let this blest assurance control,',
          'That Christ has regarded my helpless estate,',
          'And hath shed His own blood for my soul.',
        ],
      },
      {
        number: 3,
        lines: [
          'And Lord, haste the day when my faith shall be sight,',
          'The clouds be rolled back as a scroll;',
          'The trump shall resound, and the Lord shall descend,',
          'Even so, it is well with my soul.',
        ],
      },
    ],
    chorus: [
      'It is well with my soul,',
      'It is well, it is well with my soul.',
    ],
    tags: ['faith', 'peace', 'comfort', 'trust'],
    meter: '11.8.11.9 with Refrain',
    tune: 'Ville du Havre',
    key: 'C Major',
  },
  {
    number: 40,
    title: 'How Great Thou Art',
    alternateTitle: 'O Lord My God',
    category: 'Worship',
    author: 'Carl Boberg / Stuart K. Hine',
    verses: [
      {
        number: 1,
        lines: [
          'O Lord my God, when I in awesome wonder,',
          'Consider all the worlds Thy hands have made;',
          'I see the stars, I hear the rolling thunder,',
          'Thy power throughout the universe displayed.',
        ],
      },
      {
        number: 2,
        lines: [
          'When through the woods and forest glades I wander,',
          'And hear the birds sing sweetly in the trees;',
          'When I look down from lofty mountain grandeur',
          'And hear the brook and feel the gentle breeze.',
        ],
      },
      {
        number: 3,
        lines: [
          'When Christ shall come with shout of acclamation',
          'And take me home, what joy shall fill my heart!',
          'Then I shall bow in humble adoration,',
          'And then proclaim: My God, how great Thou art!',
        ],
      },
    ],
    chorus: [
      'Then sings my soul, my Savior God, to Thee,',
      'How great Thou art! How great Thou art!',
      'Then sings my soul, my Savior God, to Thee,',
      'How great Thou art! How great Thou art!',
    ],
    tags: ['worship', 'creation', 'praise'],
    meter: '11.10.11.10 with Refrain',
    tune: 'O Store Gud',
    key: 'B Flat Major',
  },
  {
    number: 41,
    title: 'Abide with Me',
    alternateTitle: 'Fast Falls the Eventide',
    category: 'Prayer',
    author: 'Henry Francis Lyte',
    verses: [
      {
        number: 1,
        lines: [
          'Abide with me: fast falls the eventide;',
          'The darkness deepens; Lord, with me abide:',
          'When other helpers fail and comforts flee,',
          'Help of the helpless, O abide with me.',
        ],
      },
      {
        number: 2,
        lines: [
          'Swift to its close ebbs out life’s little day;',
          'Earth’s joys grow dim, its glories pass away;',
          'Change and decay in all around I see;',
          'O Thou who changest not, abide with me.',
        ],
      },
      {
        number: 3,
        lines: [
          'Hold Thou Thy cross before my closing eyes;',
          'Shine through the gloom, and point me to the skies:',
          'Heaven’s morning breaks, and earth’s vain shadows flee;',
          'In life, in death, O Lord, abide with me.',
        ],
      },
    ],
    tags: ['prayer', 'evening', 'comfort', 'hope'],
    meter: '10.10.10.10',
    tune: 'Eventide',
    key: 'E Flat Major',
  },
  {
    number: 42,
    title: 'The Old Rugged Cross',
    alternateTitle: 'On a Hill Far Away',
    category: 'Salvation',
    author: 'George Bennard',
    verses: [
      {
        number: 1,
        lines: [
          'On a hill far away stood an old rugged cross,',
          'The emblem of suff’ring and shame;',
          'And I love that old cross where the dearest and best',
          'For a world of lost sinners was slain.',
        ],
      },
      {
        number: 2,
        lines: [
          'In the old rugged cross, stained with blood so divine,',
          'A wondrous beauty I see;',
          'For ’twas on that old cross Jesus suffered and died',
          'To pardon and sanctify me.',
        ],
      },
    ],
    chorus: [
      'So I’ll cherish the old rugged cross,',
      'Till my trophies at last I lay down;',
      'I will cling to the old rugged cross,',
      'And exchange it some day for a crown.',
    ],
    tags: ['salvation', 'cross', 'devotion'],
    meter: '12.8.12.8 with Refrain',
    tune: 'Old Rugged Cross',
    key: 'B Flat Major',
  },
  {
    number: 43,
    title: 'Leaning on the Everlasting Arms',
    alternateTitle: 'What a Fellowship, What a Joy Divine',
    category: 'Faith & Trust',
    author: 'Elisha A. Hoffman',
    verses: [
      {
        number: 1,
        lines: [
          'What a fellowship, what a joy divine,',
          'Leaning on the everlasting arms;',
          'What a blessedness, what a peace is mine,',
          'Leaning on the everlasting arms.',
        ],
      },
      {
        number: 2,
        lines: [
          'O how sweet to walk in this pilgrim way,',
          'Leaning on the everlasting arms;',
          'O how bright the path grows from day to day,',
          'Leaning on the everlasting arms.',
        ],
      },
    ],
    chorus: [
      'Leaning, leaning, safe and secure from all alarms;',
      'Leaning, leaning, leaning on the everlasting arms.',
    ],
    tags: ['faith', 'peace', 'security'],
    meter: '10.9.10.9 with Refrain',
    tune: 'Showalter',
    key: 'A Flat Major',
  },
  {
    number: 44,
    title: 'I Surrender All',
    alternateTitle: 'All to Jesus I Surrender',
    category: 'Dedication',
    author: 'Judson W. Van DeVenter',
    verses: [
      {
        number: 1,
        lines: [
          'All to Jesus I surrender, all to Him I freely give;',
          'I will ever love and trust Him, in His presence daily live.',
        ],
      },
      {
        number: 2,
        lines: [
          'All to Jesus I surrender, humbly at His feet I bow,',
          'Worldly pleasures all forsaken, take me, Jesus, take me now.',
        ],
      },
    ],
    chorus: [
      'I surrender all, I surrender all,',
      'All to Thee, my blessed Savior, I surrender all.',
    ],
    tags: ['dedication', 'consecration', 'surrender'],
    meter: '8.7.8.7 with Refrain',
    tune: 'Surrender',
    key: 'C Major',
  },
  {
    number: 45,
    title: 'He Leadeth Me: O Blessed Thought!',
    alternateTitle: 'Words with Heavenly Comfort Fraught',
    category: 'Prayer',
    author: 'Joseph H. Gilmore',
    verses: [
      {
        number: 1,
        lines: [
          'He leadeth me: O blessed thought!',
          'O words with heavenly comfort fraught!',
          'Whate’er I do, where’er I be,',
          'Still ’tis God’s hand that leadeth me.',
        ],
      },
      {
        number: 2,
        lines: [
          'Sometimes mid scenes of deepest gloom,',
          'Sometimes where Eden’s bowers bloom,',
          'By waters calm, o’er troubled sea,',
          'Still ’tis His hand that leadeth me.',
        ],
      },
    ],
    chorus: [
      'He leadeth me, He leadeth me,',
      'By His own hand He leadeth me:',
      'His faithful follower I would be,',
      'For by His hand He leadeth me.',
    ],
    tags: ['prayer', 'guidance', 'comfort'],
    meter: 'L.M. with Refrain',
    tune: 'He Leadeth Me',
    key: 'D Major',
  },
  {
    number: 46,
    title: 'When We All Get to Heaven',
    alternateTitle: 'Sing the Wondrous Love of Jesus',
    category: 'Praise',
    author: 'Eliza E. Hewitt',
    verses: [
      {
        number: 1,
        lines: [
          'Sing the wondrous love of Jesus, sing His mercy and His grace;',
          'In the mansions fair and happy He’s prepared for us a place.',
        ],
      },
      {
        number: 2,
        lines: [
          'While we walk the pilgrim pathway, clouds will overspread the sky;',
          'But when traveling days are over, not a shadow, not a sigh.',
        ],
      },
    ],
    chorus: [
      'When we all get to heaven, what a day of rejoicing that will be!',
      'When we all see Jesus, we’ll sing and shout the victory!',
    ],
    tags: ['praise', 'heaven', 'hope'],
    meter: '10.9.10.9 with Refrain',
    tune: 'Heaven',
    key: 'C Major',
  },
  {
    number: 47,
    title: 'There Is a Fountain Filled with Blood',
    alternateTitle: 'Drawn from Immanuel’s Veins',
    category: 'Salvation',
    author: 'William Cowper',
    verses: [
      {
        number: 1,
        lines: [
          'There is a fountain filled with blood drawn from Immanuel’s veins;',
          'And sinners plunged beneath that flood lose all their guilty stains.',
        ],
      },
      {
        number: 2,
        lines: [
          'The dying thief rejoiced to see that fountain in his day;',
          'And there may I, though vile as he, wash all my sins away.',
        ],
      },
    ],
    tags: ['salvation', 'blood', 'cleansing'],
    meter: 'C.M. (8.6.8.6)',
    tune: 'Cleansing Fountain',
    key: 'C Major',
  },
  {
    number: 48,
    title: 'Revive Us Again',
    alternateTitle: 'We Praise Thee, O God',
    category: 'Praise',
    author: 'William P. Mackay',
    verses: [
      {
        number: 1,
        lines: [
          'We praise Thee, O God, for the Son of Thy love,',
          'For Jesus who died and is now gone above.',
        ],
      },
      {
        number: 2,
        lines: [
          'We praise Thee, O God, for Thy Spirit of light,',
          'Who has shown us our Savior and scattered our night.',
        ],
      },
    ],
    chorus: [
      'Hallelujah! Thine the glory, Hallelujah! Amen;',
      'Hallelujah! Thine the glory, revive us again.',
    ],
    tags: ['praise', 'revival', 'spirit'],
    meter: '11.11 with Refrain',
    tune: 'Revive Us Again',
    key: 'F Major',
  },
  {
    number: 49,
    title: 'Open My Eyes, That I May See',
    alternateTitle: 'Glimpses of Truth Thou Hast for Me',
    category: 'Prayer',
    author: 'Clara H. Scott',
    verses: [
      {
        number: 1,
        lines: [
          'Open my eyes, that I may see glimpses of truth Thou hast for me;',
          'Place in my hands the wonderful key that shall unclasp and set me free.',
        ],
      },
      {
        number: 2,
        lines: [
          'Open my ears, that I may hear voices of truth Thou sendest clear;',
          'And while the wave-notes fall on my ear, everything false will disappear.',
        ],
      },
    ],
    chorus: [
      'Silently now I wait for Thee, ready, my God, Thy will to see;',
      'Open my eyes, illumine me, Spirit divine!',
    ],
    tags: ['prayer', 'illumination', 'spirit'],
    meter: '8.8.9.8 with Refrain',
    tune: 'Scott',
    key: 'A Flat Major',
  },
  {
    number: 50,
    title: 'Victory in Jesus',
    alternateTitle: 'I Heard an Old, Old Story',
    category: 'Salvation',
    author: 'Eugene M. Bartlett',
    verses: [
      {
        number: 1,
        lines: [
          'I heard an old, old story, how a Savior came from glory,',
          'How He gave His life on Calvary to save a wretch like me;',
          'I heard about His groaning, of His precious blood’s atoning,',
          'Then I repented of my sins and won the victory.',
        ],
      },
      {
        number: 2,
        lines: [
          'I heard about His healing, of His cleansing power revealing,',
          'How He made the lame to walk again and caused the blind to see;',
          'And then I cried, "Dear Jesus, come and heal my broken spirit,"',
          'And somehow Jesus came and brought to me the victory.',
        ],
      },
    ],
    chorus: [
      'O victory in Jesus, my Savior forever!',
      'He sought me and bought me with His redeeming blood;',
      'He loved me ere I knew Him, and all my love is due Him;',
      'He plunged me to victory beneath the cleansing flood.',
    ],
    tags: ['salvation', 'victory', 'testimony'],
    meter: '13.13.13.13 with Refrain',
    tune: 'Victory in Jesus',
    key: 'G Major',
  },
  {
    number: 51,
    title: 'Doxology (Old 100th)',
    alternateTitle: 'All People That on Earth Do Dwell',
    category: 'Praise',
    author: 'William Kethe',
    verses: [
      {
        number: 1,
        lines: [
          'All people that on earth do dwell, sing to the Lord with cheerful voice;',
          'Him serve with fear, His praise forthtell, come ye before Him and rejoice.',
        ],
      },
      {
        number: 2,
        lines: [
          'The Lord, ye know, is God indeed, without our aid He did us make;',
          'We are His folk, He doth us feed, and for His sheep He doth us take.',
        ],
      },
    ],
    tags: ['praise', 'worship', 'creature'],
    meter: 'L.M. (8.8.8.8)',
    tune: 'Old 100th',
    key: 'G Major',
  },
  {
    number: 52,
    title: 'Crown Him the Lord of Love',
    alternateTitle: 'Enthroned in Worlds Above',
    category: 'Worship',
    author: 'Godfrey Thring',
    verses: [
      {
        number: 1,
        lines: [
          'Crown Him the Lord of heav’n, enthroned in worlds above;',
          'Crown Him the King to whom is giv’n the wondrous name of Love.',
        ],
      },
      {
        number: 2,
        lines: [
          'Crown Him with many crowns, as thrones before Him fall;',
          'Crown Him, ye kings, with many crowns, for He is King of all.',
        ],
      },
    ],
    tags: ['worship', 'praise', 'king'],
    meter: 'D.S.M.',
    tune: 'Diademata',
    key: 'D Major',
  },
];
